<?php

/**
 * This is the model base class for the table "tbl_contact".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Contact".
 *
 * Columns in table "tbl_contact" available as properties of the model,
 * followed by relations of table "tbl_contact" available as properties of the model.
 *
 * @property integer $id
 * @property string $firstname
 * @property string $lastname
 * @property string $salutation
 * @property string $title
 * @property string $notes
 * @property string $telephone
 * @property string $mobile
 * @property string $switchboard
 * @property string $fax
 * @property integer $link_company_address
 * @property string $address1
 * @property string $address2
 * @property string $address3
 * @property string $address4
 * @property string $address5
 * @property string $postcode
 * @property string $region
 * @property integer $user_id
 * @property integer $company_id
 * @property string $create_time
 * @property integer $create_user_id
 * @property string $update_time
 * @property integer $update_user_id
 *
 * @property User $updateUser
 * @property Company $company
 * @property User $createUser
 * @property User $user
 * @property Attribute[] $tblAttributes
 * @property Task[] $tasks
 */
abstract class BaseContact extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_contact';
	}

	/**
	 * Behaviors
	 * @return array
	 */
	public function behaviors()
	{
		return array(
			'TimestampBehavior' => array(
				'class' => 'root.common.extensions.behaviors.TimestampBehavior'
			),
			'BlameableBehavior' => array(
				'class' => 'root.common.extensions.behaviors.BlameableBehavior.BlameableBehavior'
			),
		);
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Contact|Contacts', $n);
	}

	public static function representingColumn() {
		return 'firstname';
	}

	public function rules() {
		return array(
			array('firstname, lastname, salutation, title, notes', 'required'),
			array('link_company_address, user_id, company_id, create_user_id, update_user_id', 'numerical', 'integerOnly'=>true),
			array('firstname, lastname, salutation, title, telephone, mobile, switchboard, fax, address1, address2, address3, address4, address5, postcode, region', 'length', 'max'=>255),
			array('create_time, update_time', 'safe'),
			array('telephone, mobile, switchboard, fax, link_company_address, address1, address2, address3, address4, address5, postcode, region, user_id, company_id, create_time, create_user_id, update_time, update_user_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, firstname, lastname, salutation, title, notes, telephone, mobile, switchboard, fax, link_company_address, address1, address2, address3, address4, address5, postcode, region, user_id, company_id, create_time, create_user_id, update_time, update_user_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'updateUser' => array(self::BELONGS_TO, 'User', 'update_user_id'),
			'company' => array(self::BELONGS_TO, 'Company', 'company_id'),
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
			'tblAttributes' => array(self::MANY_MANY, 'Attribute', 'tbl_contact_attribute_assignment(contact_id, attribute_id)'),
			'tasks' => array(self::HAS_MANY, 'Task', 'contact_id'),
		);
	}

	public function pivotModels() {
		return array(
			'tblAttributes' => 'ContactAttributeAssignment',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'firstname' => Yii::t('app', 'Firstname'),
			'lastname' => Yii::t('app', 'Lastname'),
			'salutation' => Yii::t('app', 'Salutation'),
			'title' => Yii::t('app', 'Title'),
			'notes' => Yii::t('app', 'Notes'),
			'telephone' => Yii::t('app', 'Telephone'),
			'mobile' => Yii::t('app', 'Mobile'),
			'switchboard' => Yii::t('app', 'Switchboard'),
			'fax' => Yii::t('app', 'Fax'),
			'link_company_address' => Yii::t('app', 'Link Company Address'),
			'address1' => Yii::t('app', 'Address1'),
			'address2' => Yii::t('app', 'Address2'),
			'address3' => Yii::t('app', 'Address3'),
			'address4' => Yii::t('app', 'Address4'),
			'address5' => Yii::t('app', 'Address5'),
			'postcode' => Yii::t('app', 'Postcode'),
			'region' => Yii::t('app', 'Region'),
			'user_id' => null,
			'company_id' => null,
			'create_time' => Yii::t('app', 'Create Time'),
			'create_user_id' => null,
			'update_time' => Yii::t('app', 'Update Time'),
			'update_user_id' => null,
			'updateUser' => null,
			'company' => null,
			'createUser' => null,
			'user' => null,
			'tblAttributes' => null,
			'tasks' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('firstname', $this->firstname, true);
		$criteria->compare('lastname', $this->lastname, true);
		$criteria->compare('salutation', $this->salutation, true);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('notes', $this->notes, true);
		$criteria->compare('telephone', $this->telephone, true);
		$criteria->compare('mobile', $this->mobile, true);
		$criteria->compare('switchboard', $this->switchboard, true);
		$criteria->compare('fax', $this->fax, true);
		$criteria->compare('link_company_address', $this->link_company_address);
		$criteria->compare('address1', $this->address1, true);
		$criteria->compare('address2', $this->address2, true);
		$criteria->compare('address3', $this->address3, true);
		$criteria->compare('address4', $this->address4, true);
		$criteria->compare('address5', $this->address5, true);
		$criteria->compare('postcode', $this->postcode, true);
		$criteria->compare('region', $this->region, true);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('company_id', $this->company_id);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('update_user_id', $this->update_user_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}