<?php

/**
 * This is the model base class for the table "tbl_task".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Task".
 *
 * Columns in table "tbl_task" available as properties of the model,
 * followed by relations of table "tbl_task" available as properties of the model.
 *
 * @property integer $id
 * @property string $type
 * @property string $notes
 * @property integer $contact_id
 * @property integer $owner_id
 * @property string $due_time
 * @property string $completed_time
 * @property integer $campaign_id
 * @property string $create_time
 * @property integer $create_user_id
 * @property string $update_time
 * @property integer $update_user_id
 *
 * @property Campaign $campaign
 * @property Contact $contact
 * @property User $createUser
 * @property User $owner
 * @property User $updateUser
 */
abstract class BaseTask extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_task';
	}

	/**
	 * Behaviors
	 * @return array
	 */
	public function behaviors()
	{
		return array(
			'BlameableBehavior' => array(
			'class' => 'root.common.extensions.behaviors.BlameableBehavior.BlameableBehavior'
			),
		);
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Task|Tasks', $n);
	}

	public static function representingColumn() {
		return 'type';
	}

	public function rules() {
		return array(
			array('contact_id, owner_id, campaign_id, create_user_id, update_user_id', 'numerical', 'integerOnly'=>true),
			array('type', 'length', 'max'=>255),
			array('notes, due_time, completed_time, create_time, update_time', 'safe'),
			array('type, notes, contact_id, owner_id, due_time, completed_time, campaign_id, create_time, create_user_id, update_time, update_user_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, type, notes, contact_id, owner_id, due_time, completed_time, campaign_id, create_time, create_user_id, update_time, update_user_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'campaign' => array(self::BELONGS_TO, 'Campaign', 'campaign_id'),
			'contact' => array(self::BELONGS_TO, 'Contact', 'contact_id'),
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'owner' => array(self::BELONGS_TO, 'User', 'owner_id'),
			'updateUser' => array(self::BELONGS_TO, 'User', 'update_user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'type' => Yii::t('app', 'Type'),
			'notes' => Yii::t('app', 'Notes'),
			'contact_id' => null,
			'owner_id' => null,
			'due_time' => Yii::t('app', 'Due Time'),
			'completed_time' => Yii::t('app', 'Completed Time'),
			'campaign_id' => null,
			'create_time' => Yii::t('app', 'Create Time'),
			'create_user_id' => null,
			'update_time' => Yii::t('app', 'Update Time'),
			'update_user_id' => null,
			'campaign' => null,
			'contact' => null,
			'createUser' => null,
			'owner' => null,
			'updateUser' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('type', $this->type, true);
		$criteria->compare('notes', $this->notes, true);
		$criteria->compare('contact_id', $this->contact_id);
		$criteria->compare('owner_id', $this->owner_id);
		$criteria->compare('due_time', $this->due_time, true);
		$criteria->compare('completed_time', $this->completed_time, true);
		$criteria->compare('campaign_id', $this->campaign_id);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('update_user_id', $this->update_user_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}