<?php

/**
 * This is the model base class for the table "tbl_campaign".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Campaign".
 *
 * Columns in table "tbl_campaign" available as properties of the model,
 * followed by relations of table "tbl_campaign" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $type
 * @property string $asset
 * @property string $notes
 * @property string $create_time
 * @property integer $create_user_id
 * @property string $update_time
 * @property integer $update_user_id
 *
 * @property User $updateUser
 * @property User $createUser
 * @property Task[] $tasks
 */
abstract class BaseCampaign extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tbl_campaign';
	}

	/**
	 * Behaviors
	 * @return array
	 */
	public function behaviors()
	{
		return array(
			'BlameableBehavior' => array(
			'class' => 'root.common.extensions.behaviors.BlameableBehavior.BlameableBehavior'
			),
		);
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Campaign|Campaigns', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, type', 'required'),
			array('create_user_id, update_user_id', 'numerical', 'integerOnly'=>true),
			array('name, type, asset', 'length', 'max'=>255),
			array('notes, create_time, update_time', 'safe'),
			array('asset, notes, create_time, create_user_id, update_time, update_user_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, type, asset, notes, create_time, create_user_id, update_time, update_user_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'updateUser' => array(self::BELONGS_TO, 'User', 'update_user_id'),
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'tasks' => array(self::HAS_MANY, 'Task', 'campaign_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'type' => Yii::t('app', 'Type'),
			'asset' => Yii::t('app', 'Asset'),
			'notes' => Yii::t('app', 'Notes'),
			'create_time' => Yii::t('app', 'Create Time'),
			'create_user_id' => null,
			'update_time' => Yii::t('app', 'Update Time'),
			'update_user_id' => null,
			'updateUser' => null,
			'createUser' => null,
			'tasks' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('type', $this->type, true);
		$criteria->compare('asset', $this->asset, true);
		$criteria->compare('notes', $this->notes, true);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('update_user_id', $this->update_user_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}